version: "3"

tasks:
  create-release:
    cmds:
      - git checkout -b {{.BRANCH}}
      - echo v{{.CALVER}}>VERSION
      - git add VERSION
      - git commit -m "{{.MSG}}"
      - git push --set-upstream origin {{.BRANCH}}
      - task: to_release
        vars:
          STAGE: 'prod'
          SUBSYSTEM: 'events'
      - git checkout {{.BRANCH}}
      - task: to_release
        vars:
          STAGE: 'prod'
          SUBSYSTEM: 'webapp'
      - git checkout main
      - gh pr create -w -a "@me" --base main --head {{.BRANCH}} --title "{{.MSG}}"
    vars:
      BRANCH: "release/v{{.CALVER}}"
      CALVER:
        sh: py -c "import datetime; print(datetime.date.today().strftime('%y.%m'))"
      CURRENT:
        sh: git rev-parse --abbrev-ref HEAD
      MSG: "Bump up to v{{.CALVER}}"
    preconditions:
      - sh: "[[ {{.CURRENT}} =~ ^(main|HEAD)$ ]]"
        msg: このタスクは "main" ブランチ or HEADで実行できます。 "{{.CURRENT}}" では実行できません。

  to_release:
    cmds:
      - git checkout -b {{.PR_HEAD}}
      - git push --set-upstream origin {{.PR_HEAD}}
    vars:
      SHA:
        sh: t=`git rev-parse --short HEAD`; echo ${t:0:7}
      STAGE: '{{default "stg" .STAGE}}'
      SUBSYSTEM: '{{default "events" .SUBSYSTEM}}'
      PR_HEAD: "deploy/{{.SHA}}/{{.STAGE}}/{{.SUBSYSTEM}}"
