version: "3"

tasks:
  create-release:
    cmds:
      - git checkout -b release/v{{.CALVER}}
      - echo v{{.CALVER}}>VERSION
      - git add VERSION
      - git commit -m "Bump up to v{{.CALVER}}."
      - git push --set-upstream origin release/v{{.CALVER}}
      - task: to_release
        vars:
          STAGE: 'prod'
          SUBSYSTEM: 'events'
      - task: to_release
        vars:
          STAGE: 'prod'
          SUBSYSTEM: 'webapp'
      - git checkout main
    vars:
      CALVER:
        sh: py -c "import datetime; print(datetime.date.today().strftime('%y.%m'))"
      CURRENT:
        sh: git rev-parse --abbrev-ref HEAD
    preconditions:
      - sh: "[[ {{.CURRENT}} =~ ^(main|HEAD)$ ]]"
        msg: このタスクは "main" ブランチ or HEADで実行できます。 "{{.CURRENT}}" では実行できません。

  to_release:
    cmds:
      - git checkout -b {{.PR_HEAD}}
      - git push --set-upstream origin {{.PR_HEAD}}
      - git checkout {{.CURRENT}}
    vars:
      CURRENT:
        sh: git rev-parse --abbrev-ref HEAD
      SHA:
        sh: t=`git rev-parse --short HEAD`; echo ${t:0:7}
      STAGE: '{{default "stg" .STAGE}}'
      SUBSYSTEM: '{{default "events" .SUBSYSTEM}}'
      PR_HEAD: "deploy/{{.SHA}}/{{.STAGE}}/{{.SUBSYSTEM}}"
