version: "3"

tasks:
  create-release:
    cmds:
      - echo {{.CAL_VER}}>VERSION
      - git add VERSION
      - git commit -m "{{.MSG}}"
      - git push --set-upstream origin {{.BRANCH}}
      - task: to_release
        vars:
          BACK_BRANCH: '{{.BRANCH}}'
          STAGE: 'prod'
          SUBSYSTEM: 'events'
      - task: to_release
        vars:
          BACK_BRANCH: 'main'
          STAGE: 'prod'
          SUBSYSTEM: 'webapp'
      - gh pr create -w -a "@me" --base main --head {{.BRANCH}} --title "{{.MSG}}"
      - git branch -D {{.BRANCH}}
    vars:
      CURRENT:
        sh: git rev-parse --abbrev-ref HEAD
      CAL_VER:
        sh: ver={{.CURRENT}}; echo ${ver:8}
      BRANCH: "release/{{.CAL_VER}}"
      MSG: "Bump up to {{.CAL_VER}}"
    preconditions:
      - sh: "[[ {{.CURRENT}} =~ ^release/v\\d+(\\.\\d+){1,2}$ ]]"
        msg: このタスクは "release/vXX.YY" ブランチで実行できます。 "{{.CURRENT}}" では実行できません。

  to_release:
    cmds:
      - git checkout -b {{.PR_HEAD}}
      - git push --set-upstream origin {{.PR_HEAD}}
      - git checkout {{.BACK_BRANCH}}
      - git branch -D {{.PR_HEAD}}
    vars:
      SHA:
        sh: t=`git rev-parse --short HEAD`; echo ${t:0:7}
      STAGE: '{{default "stg" .STAGE}}'
      SUBSYSTEM: '{{default "events" .SUBSYSTEM}}'
      PR_HEAD: "deploy/{{.SHA}}/{{.STAGE}}/{{.SUBSYSTEM}}"
      BACK_BRANCH: '{{default "main" .BACK_BRANCH}}'
